version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: exam-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: exam-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exam-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/exam-platform
      - JWT_SECRET=exam-platform-secret-key-change-in-prod
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - exam_backend_node_modules:/app/node_modules
    command:
      [
        "sh",
        "-c",
        "npm install --no-audit --no-fund && exec npx tsx watch src/server.ts",
      ]


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exam-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules


volumes:
  mongo-data:
  exam_backend_node_modules:
